ALTER TABLE app_users
ADD COLUMN can_access_children BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE app_users
SET can_access_children = TRUE
WHERE roles LIKE '%admin%';

CREATE TABLE children_ministry_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_name VARCHAR(160) NOT NULL,
    guardian_name VARCHAR(160),
    guardian_phone VARCHAR(40),
    age INTEGER,
    neighborhood VARCHAR(120),
    city VARCHAR(120) NOT NULL,
    activity_name VARCHAR(160),
    notes CLOB,
    responsible_user_id BIGINT NOT NULL REFERENCES app_users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(180) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR(180)
);
