CREATE TABLE social_assistance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assisted_person_name VARCHAR(160) NOT NULL,
  phone VARCHAR(40),
  age INTEGER,
  neighborhood VARCHAR(120),
  city VARCHAR(120) NOT NULL,
  service_type VARCHAR(60) NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  notes CLOB,
  responsible_user_id BIGINT NOT NULL REFERENCES app_users(id),
  team_id BIGINT NOT NULL REFERENCES teams(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(180) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  updated_by VARCHAR(180)
);

CREATE INDEX idx_social_assistance_created_at ON social_assistance_records(created_at);
CREATE INDEX idx_social_assistance_team ON social_assistance_records(team_id);
CREATE INDEX idx_social_assistance_responsible ON social_assistance_records(responsible_user_id);
CREATE INDEX idx_social_assistance_service_type ON social_assistance_records(service_type);
CREATE INDEX idx_social_assistance_neighborhood ON social_assistance_records(neighborhood);
