ALTER TABLE territories ADD COLUMN generated BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE territories ADD COLUMN distribution_version VARCHAR(80);
ALTER TABLE territories ADD COLUMN published_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE household_visits ADD COLUMN client_reference VARCHAR(80);
CREATE UNIQUE INDEX uq_household_visits_client_reference ON household_visits(client_reference);

CREATE TABLE territory_distribution_drafts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by_user_id BIGINT NOT NULL,
  requested_team_count INTEGER NOT NULL,
  payload_json CLOB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(created_by_user_id)
);
