CREATE TABLE teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  roles VARCHAR(255) NOT NULL,
  team_id BIGINT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE household_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_name VARCHAR(160) NOT NULL,
  phone VARCHAR(40),
  street VARCHAR(180),
  number VARCHAR(40),
  neighborhood VARCHAR(120),
  city VARCHAR(120) NOT NULL,
  manual_address CLOB,
  latitude DOUBLE,
  longitude DOUBLE,
  wants_visits BOOLEAN NOT NULL,
  notes CLOB,
  responsible_user_id BIGINT NOT NULL,
  team_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(180) NOT NULL,
  updated_at TIMESTAMP,
  updated_by VARCHAR(180)
);

INSERT INTO teams(id, name) VALUES (1, 'Equipe Inicial');
INSERT INTO app_users(id, name, email, password_hash, roles, team_id, active, created_at)
VALUES (1, 'Administrador', 'admin@vindesertao.local', '$2a$10$A2xXsxJ5ArnHMGfdsRlsBeGI25JAR1NbQwCqj5N7iL3VZor5Q38jq', 'admin', 1, TRUE, CURRENT_TIMESTAMP);
