CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT,
  actor_email VARCHAR(180),
  action VARCHAR(80) NOT NULL,
  entity_type VARCHAR(80) NOT NULL,
  entity_id BIGINT,
  before_data CLOB,
  after_data CLOB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_team_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  old_team_id BIGINT,
  old_team_name VARCHAR(120),
  new_team_id BIGINT,
  new_team_name VARCHAR(120),
  changed_by_user_id BIGINT,
  changed_by_email VARCHAR(180),
  changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE territories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(140) NOT NULL,
  team_id BIGINT NOT NULL,
  color VARCHAR(20) NOT NULL DEFAULT '#276749',
  polygon_geojson CLOB NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  enforce_for_projectists BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);
